root: /newjoy.co.jp/html/
admin_dir: rurupopo888/
tpl: /newjoy.co.jp/html/user_data/packages/default/
admin_tpl: /newjoy.co.jp/html/user_data/packages/admin/
image_path: /newjoy.co.jp/html/upload/save_image/
root_dir: /home/kir021669/public_html/newjoy.co.jp
root_urlpath: /newjoy.co.jp/html
template_code: default
admin_route: admin
user_data_route: user_data
public_path: /html
public_path_realdir: /home/kir021669/public_html/newjoy.co.jp/html
image_save_realdir: /home/kir021669/public_html/newjoy.co.jp/html/upload/save_image
image_temp_realdir: /home/kir021669/public_html/newjoy.co.jp/html/upload/temp_image
user_data_realdir: /home/kir021669/public_html/newjoy.co.jp/html/user_data
block_default_realdir: /home/kir021669/public_html/newjoy.co.jp/src/Eccube/Resource/template/default/Block
block_realdir: /home/kir021669/public_html/newjoy.co.jp/app/template/default/Block
template_default_realdir: /home/kir021669/public_html/newjoy.co.jp/src/Eccube/Resource/template/default
template_default_html_realdir: /home/kir021669/public_html/newjoy.co.jp/html/template/default
template_admin_realdir: /home/kir021669/public_html/newjoy.co.jp/src/Eccube/Resource/template/admin
template_admin_html_realdir: /home/kir021669/public_html/newjoy.co.jp/html/template/admin
template_realdir: /home/kir021669/public_html/newjoy.co.jp/app/template/default
template_html_realdir: /home/kir021669/public_html/newjoy.co.jp/html/template/default
template_temp_realdir: /home/kir021669/public_html/newjoy.co.jp/app/cache/eccube/template
csv_temp_realdir: /home/kir021669/public_html/newjoy.co.jp/app/cache/eccube/csv
plugin_realdir: /home/kir021669/public_html/newjoy.co.jp/app/Plugin
plugin_temp_realdir: /home/kir021669/public_html/newjoy.co.jp/app/cache/plugin
plugin_html_realdir: /home/kir021669/public_html/newjoy.co.jp/html/plugin
admin_urlpath: /newjoy.co.jp/html/template/admin
front_urlpath: /newjoy.co.jp/html/template/default
image_save_urlpath: /newjoy.co.jp/html/upload/save_image
image_temp_urlpath: /newjoy.co.jp/html/upload/temp_image
user_data_urlpath: /newjoy.co.jp/html/user_data
plugin_urlpath: /newjoy.co.jp/html/plugin
